package Main;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

interface user{
   public static String name = "";
     
}

class Kullanici{
    private String tcno;
    private String parola;

    public String getTcno() {
        return tcno;
    }

    public void setTcno(String tcno) {
        this.tcno = tcno;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }

    public Kullanici(String tcno, String parola) {
        this.tcno = tcno;
        this.parola = parola;
    }
}

public class HastaneOtomasyonu extends javax.swing.JFrame {
    private static Map<String,String> user_list = new HashMap<String,String>();

    public static Map<String, String> getUser_list() {
        return user_list;
    }
    public static void setUser_list(Map<String, String> user_list) {
        HastaneOtomasyonu.user_list = user_list;
    }
    
  
    public HastaneOtomasyonu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hastaGirisiPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tc_alani = new javax.swing.JTextField();
        sifre_alani = new javax.swing.JPasswordField();
        kayit_btn = new javax.swing.JButton();
        giris_btn = new javax.swing.JButton();
        tc_label = new javax.swing.JLabel();
        parola_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tc_alaniS = new javax.swing.JTextField();
        sifre_alaniS = new javax.swing.JPasswordField();
        giris_btnS = new javax.swing.JButton();
        tc_labelS = new javax.swing.JLabel();
        parola_labelS = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tc_alani_idari = new javax.swing.JTextField();
        sifre_alani_idari = new javax.swing.JPasswordField();
        giris_btn_idari = new javax.swing.JButton();
        tc_labelI = new javax.swing.JLabel();
        parola_labelI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tc_alaniY = new javax.swing.JTextField();
        sifre_alaniY = new javax.swing.JPasswordField();
        giris_btnY = new javax.swing.JButton();
        tc_labelY = new javax.swing.JLabel();
        parola_labelY = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        hastaGirisiPanel.setBackground(new java.awt.Color(204, 204, 204));
        hastaGirisiPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hastaGirisiPanel.setForeground(new java.awt.Color(102, 0, 0));
        hastaGirisiPanel.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        kayit_btn.setBackground(new java.awt.Color(204, 204, 204));
        kayit_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        kayit_btn.setForeground(new java.awt.Color(102, 0, 0));
        kayit_btn.setText("KAYIT OL");
        kayit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_btnActionPerformed(evt);
            }
        });

        giris_btn.setBackground(new java.awt.Color(204, 204, 204));
        giris_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        giris_btn.setForeground(new java.awt.Color(102, 0, 0));
        giris_btn.setText("GİRİŞ YAP");
        giris_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_btnActionPerformed(evt);
            }
        });

        tc_label.setBackground(new java.awt.Color(102, 102, 102));
        tc_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tc_label.setForeground(new java.awt.Color(255, 255, 255));
        tc_label.setText("T.C. KİMLİK NO:");

        parola_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        parola_label.setForeground(new java.awt.Color(255, 255, 255));
        parola_label.setText("PAROLA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parola_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kayit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(giris_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(sifre_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc_label)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parola_label)
                            .addComponent(sifre_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kayit_btn)
                    .addComponent(giris_btn))
                .addGap(41, 41, 41))
        );

        hastaGirisiPanel.addTab("Hasta Giriş", jPanel1);

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));

        giris_btnS.setBackground(new java.awt.Color(204, 204, 204));
        giris_btnS.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        giris_btnS.setForeground(new java.awt.Color(102, 0, 0));
        giris_btnS.setText("GİRİŞ YAP");
        giris_btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_btnSActionPerformed(evt);
            }
        });

        tc_labelS.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tc_labelS.setText("T.C. KİMLİK NO:");

        parola_labelS.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        parola_labelS.setText("PAROLA:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tc_labelS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parola_labelS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifre_alaniS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_alaniS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(giris_btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc_labelS)
                    .addComponent(tc_alaniS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parola_labelS)
                    .addComponent(sifre_alaniS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(giris_btnS)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        hastaGirisiPanel.addTab("Sağlık Elemanı Giriş", jPanel2);

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));

        giris_btn_idari.setBackground(new java.awt.Color(204, 204, 204));
        giris_btn_idari.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        giris_btn_idari.setForeground(new java.awt.Color(102, 0, 0));
        giris_btn_idari.setText("GİRİŞ YAP");
        giris_btn_idari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_btn_idariActionPerformed(evt);
            }
        });

        tc_labelI.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tc_labelI.setForeground(new java.awt.Color(255, 255, 255));
        tc_labelI.setText("T.C. KİMLİK NO:");

        parola_labelI.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        parola_labelI.setForeground(new java.awt.Color(255, 255, 255));
        parola_labelI.setText("PAROLA:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parola_labelI, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_labelI))
                .addGap(76, 76, 76)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifre_alani_idari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_alani_idari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(giris_btn_idari, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tc_labelI)
                    .addComponent(tc_alani_idari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parola_labelI)
                    .addComponent(sifre_alani_idari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(giris_btn_idari)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hastaGirisiPanel.addTab("İdari Personel Giriş", jPanel3);

        jPanel7.setBackground(new java.awt.Color(102, 0, 0));

        giris_btnY.setBackground(new java.awt.Color(204, 204, 204));
        giris_btnY.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        giris_btnY.setForeground(new java.awt.Color(102, 0, 0));
        giris_btnY.setText("GİRİŞ YAP");
        giris_btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_btnYActionPerformed(evt);
            }
        });

        tc_labelY.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tc_labelY.setForeground(new java.awt.Color(255, 255, 255));
        tc_labelY.setText("T.C. KİMLİK NO:");

        parola_labelY.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        parola_labelY.setForeground(new java.awt.Color(255, 255, 255));
        parola_labelY.setText("PAROLA:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parola_labelY, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_labelY, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifre_alaniY, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_alaniY, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(giris_btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc_alaniY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_labelY))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parola_labelY)
                    .addComponent(sifre_alaniY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(giris_btnY)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        hastaGirisiPanel.addTab("Yönetici Giriş", jPanel4);

        getContentPane().add(hastaGirisiPanel);
        hastaGirisiPanel.setBounds(0, 370, 650, 270);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zehra\\OneDrive\\Resimler\\Ekran Görüntüleri\\2022-12-10.png")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -20, 650, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giris_btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_btnYActionPerformed
        // TODO add your handling code here: 
       
    }//GEN-LAST:event_giris_btnYActionPerformed

    private void giris_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_btnActionPerformed
       
        String tcno = tc_alani.getText();
        String parola = new String(sifre_alani.getPassword());
        
        Map<String,String> user_list = new HashMap<String,String>();
        
         user_list.put("12345678910", "123");
         user_list.put("12345678911", "1234");
         user_list.put("12345678912", "12345");
         user_list.put("12345678913", "123456");
       
        if(user_list.isEmpty()){
            JOptionPane.showMessageDialog(this, "HİÇBİR KULLANICI BULUNAMADI.");
         }
        else{
         
            for(Map.Entry<String,String> entry : user_list.entrySet()){
                
                if(user_list.containsKey(tcno) && user_list.containsValue(parola)){
                    
                    JOptionPane.showMessageDialog(this, "HOŞ GELDİNİZ..."+tcno);
                    
                    HastaGiris girisHasta = new HastaGiris();
                    girisHasta.show();
                    dispose();
                    
                    return;
                } 
                else if(user_list.equals("12345678910") && user_list.equals("123") 
                        ||user_list.equals("12345678911") && user_list.equals("1234")
                        ||user_list.equals("12345678912") && user_list.equals("12345")
                          ||user_list.equals("12345678913") && user_list.equals("123456")){
                    
                }
                 JOptionPane.showMessageDialog(this, "HOŞ GELDİNİZ..."+tcno);
              }
            JOptionPane.showMessageDialog(this, "BÖYLE BİR KULLANICI YOK.");
                
            }
        
       
    }//GEN-LAST:event_giris_btnActionPerformed

    private void kayit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_btnActionPerformed
       
        HastaGirisKayit hastakayit = new HastaGirisKayit();
        hastakayit.setVisible(true);
         if(tc_alani.getText().length()==0 || sifre_alani.getText().length()==0){
           Kontrol.showMsg("fill");
         }
        
    }//GEN-LAST:event_kayit_btnActionPerformed

    private void giris_btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_btnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giris_btnSActionPerformed

    private void giris_btn_idariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_btn_idariActionPerformed
        
        IdariPersonelGiris idari = new IdariPersonelGiris();
        idari.show();
        dispose();
        
        
    }//GEN-LAST:event_giris_btn_idariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaneOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaneOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaneOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaneOtomasyonu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaneOtomasyonu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton giris_btn;
    private javax.swing.JButton giris_btnS;
    private javax.swing.JButton giris_btnY;
    private javax.swing.JButton giris_btn_idari;
    private javax.swing.JTabbedPane hastaGirisiPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton kayit_btn;
    private javax.swing.JLabel parola_label;
    private javax.swing.JLabel parola_labelI;
    private javax.swing.JLabel parola_labelS;
    private javax.swing.JLabel parola_labelY;
    private javax.swing.JPasswordField sifre_alani;
    private javax.swing.JPasswordField sifre_alaniS;
    private javax.swing.JPasswordField sifre_alaniY;
    private javax.swing.JPasswordField sifre_alani_idari;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField tc_alaniS;
    private javax.swing.JTextField tc_alaniY;
    private javax.swing.JTextField tc_alani_idari;
    private javax.swing.JLabel tc_label;
    private javax.swing.JLabel tc_labelI;
    private javax.swing.JLabel tc_labelS;
    private javax.swing.JLabel tc_labelY;
    // End of variables declaration//GEN-END:variables
}
