/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gökçe
 */
public class IdariPersonelGiris extends javax.swing.JFrame {

    /**
     * Creates new form IdariPersonelGiris
     */
    public IdariPersonelGiris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personel_cb = new javax.swing.JComboBox<>();
        personel_label = new javax.swing.JLabel();
        ekle_btn = new javax.swing.JButton();
        guncelle_btn = new javax.swing.JButton();
        sil_btn = new javax.swing.JButton();
        geri_btn = new javax.swing.JButton();
        tc_label = new javax.swing.JLabel();
        maas_label = new javax.swing.JLabel();
        personel_tc = new javax.swing.JTextField();
        personel_maas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personel_tablosu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        personel_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOKTOR", "HEMŞİRE", "İDARİ PERSONEL", " " }));
        personel_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_cbActionPerformed(evt);
            }
        });

        personel_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        personel_label.setForeground(new java.awt.Color(255, 255, 255));
        personel_label.setText("SAĞLIK ÇALIŞANI SEÇ");

        ekle_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        ekle_btn.setText("EKLE");
        ekle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_btnActionPerformed(evt);
            }
        });

        guncelle_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        guncelle_btn.setText("GÜNCELLE");
        guncelle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_btnActionPerformed(evt);
            }
        });

        sil_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        sil_btn.setText("SİL");
        sil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_btnActionPerformed(evt);
            }
        });

        geri_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        geri_btn.setText("GİRİŞ SAYFASINA DÖN");
        geri_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_btnActionPerformed(evt);
            }
        });

        tc_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tc_label.setForeground(new java.awt.Color(255, 255, 255));
        tc_label.setText("PERSONEL T.C. :");

        maas_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        maas_label.setForeground(new java.awt.Color(255, 255, 255));
        maas_label.setText("MAAŞ :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maas_label, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geri_btn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekle_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(sil_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personel_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personel_maas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personel_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_label)
                    .addComponent(personel_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personel_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc_label))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maas_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(ekle_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(geri_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guncelle_btn)
                        .addGap(18, 18, 18)
                        .addComponent(sil_btn)
                        .addGap(31, 31, 31))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        personel_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÜNVAN", "T.C. KİMLİK NO", "MAAŞ"
            }
        ));
        personel_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personel_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personel_tablosu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personel_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_cbActionPerformed

    private void geri_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_btnActionPerformed
        
        HastaneOtomasyonu geri = new HastaneOtomasyonu();
        geri.show();
        dispose();
    }//GEN-LAST:event_geri_btnActionPerformed

    private void ekle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_btnActionPerformed
        
       DefaultTableModel model = (DefaultTableModel) personel_tablosu.getModel();
       
        Object[] eklenecek = { personel_cb.getSelectedItem().toString(),personel_tc.getText(),personel_maas.getText()};
        model.addRow(eklenecek);
    }//GEN-LAST:event_ekle_btnActionPerformed

    private void guncelle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_btnActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) personel_tablosu.getModel();
        int secili_row = personel_tablosu.getSelectedRow();
        
        if(secili_row == -1){
            if(personel_tablosu.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "TABLO BOŞ");
            }
            else{
                JOptionPane.showMessageDialog(this, "GÜNCELLENECEK VERİYİ SEÇİNİZ");   
            }
        }
        else{
            model.setValueAt(personel_cb.getSelectedItem().toString(), secili_row, 0);
            model.setValueAt(personel_tc.getText(), secili_row, 1);
            model.setValueAt(personel_maas.getText(), secili_row, 2);    
        }
        
    }//GEN-LAST:event_guncelle_btnActionPerformed

    private void sil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_btnActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) personel_tablosu.getModel();
        int secili_row = personel_tablosu.getSelectedRow();
        
        if(secili_row == -1){
            if(personel_tablosu.getRowCount() != 0){
                JOptionPane.showMessageDialog(this, "SİLİNECEK KİŞİYİ SEÇİNİZ");  
            } 
        }
        else{
            model.removeRow(secili_row);
        }
       
        
    }//GEN-LAST:event_sil_btnActionPerformed

    private void personel_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personel_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) personel_tablosu.getModel();
        int secili_row = personel_tablosu.getSelectedRow();
        
        personel_cb.setSelectedItem(model.getValueAt(secili_row, 0).toString());
        personel_tc.setText(model.getValueAt(secili_row, 1).toString());
        personel_maas.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_personel_tablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdariPersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdariPersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdariPersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdariPersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdariPersonelGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle_btn;
    private javax.swing.JButton geri_btn;
    private javax.swing.JButton guncelle_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maas_label;
    private javax.swing.JComboBox<String> personel_cb;
    private javax.swing.JLabel personel_label;
    private javax.swing.JTextField personel_maas;
    private javax.swing.JTable personel_tablosu;
    private javax.swing.JTextField personel_tc;
    private javax.swing.JButton sil_btn;
    private javax.swing.JLabel tc_label;
    // End of variables declaration//GEN-END:variables
}
