/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gökçe
 */
public class SaglikCalisaniGiris extends javax.swing.JFrame {

    /**
     * Creates new form SaglikCalisaniGiris
     */
    public SaglikCalisaniGiris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geriyeDon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hastaTablosu = new javax.swing.JTable();
        hasta_tc_label = new javax.swing.JLabel();
        teshis_label = new javax.swing.JLabel();
        ilac_label = new javax.swing.JLabel();
        randevu_label = new javax.swing.JLabel();
        tcField = new javax.swing.JTextField();
        teshisField = new javax.swing.JTextField();
        ilacField = new javax.swing.JTextField();
        randevuField = new javax.swing.JTextField();
        hastaEkle_btn = new javax.swing.JButton();
        guncelle_btn = new javax.swing.JButton();
        sil_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        geriyeDon.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        geriyeDon.setText("ANA MENÜYE DÖN");
        geriyeDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriyeDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(geriyeDon, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(geriyeDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        hastaTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HASTA T.C.", "TEŞHİS", "İLAÇ", "RANDEVU TARİHİ"
            }
        ));
        hastaTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hastaTablosu);

        hasta_tc_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        hasta_tc_label.setText("HASTA T.C. :");

        teshis_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        teshis_label.setText("TEŞHİS:");

        ilac_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        ilac_label.setText("VERİLEN İLAÇ:");

        randevu_label.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        randevu_label.setText("RANDEVU TARİHİ:");

        tcField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcFieldActionPerformed(evt);
            }
        });

        ilacField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilacFieldActionPerformed(evt);
            }
        });

        hastaEkle_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        hastaEkle_btn.setText("HASTA EKLE");
        hastaEkle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaEkle_btnActionPerformed(evt);
            }
        });

        guncelle_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        guncelle_btn.setText("GÜNCELLE");
        guncelle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_btnActionPerformed(evt);
            }
        });

        sil_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        sil_btn.setText("HASTA SİL");
        sil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randevu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilac_label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teshis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasta_tc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sil_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guncelle_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hastaEkle_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                                .addGap(232, 232, 232))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ilacField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tcField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teshisField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(randevuField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasta_tc_label)
                    .addComponent(tcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teshis_label)
                    .addComponent(teshisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ilac_label)
                            .addComponent(ilacField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(randevu_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(randevuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hastaEkle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(guncelle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sil_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hastaEkle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaEkle_btnActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) hastaTablosu.getModel();
        Object[] eklenecek = { tcField.getText(),teshisField.getText(),ilacField.getText(),randevuField.getText()};
        model.addRow(eklenecek);
        
    }//GEN-LAST:event_hastaEkle_btnActionPerformed

    private void tcFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcFieldActionPerformed

    private void ilacFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilacFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ilacFieldActionPerformed

    private void geriyeDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriyeDonActionPerformed
        
        HastaneOtomasyonu geriye = new HastaneOtomasyonu();
        geriye.show();
        dispose();
        
        
    }//GEN-LAST:event_geriyeDonActionPerformed

    private void guncelle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_btnActionPerformed
      
        DefaultTableModel model = (DefaultTableModel) hastaTablosu.getModel();
        int secili_row = hastaTablosu.getSelectedRow();
        
       if(secili_row == -1){
            if(hastaTablosu.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "TABLO BOŞ");
            }
            else{
                JOptionPane.showMessageDialog(this, "GÜNCELLENECEK VERİYİ SEÇİNİZ");   
            }
        }
        else{
           model.setValueAt(tcField.getText(), secili_row, 0);
            model.setValueAt(teshisField.getText(), secili_row, 1);
            model.setValueAt(ilacField.getText(), secili_row, 2);
            model.setValueAt(randevuField.getText(), secili_row, 3);
        
        }
        
        
        
    }//GEN-LAST:event_guncelle_btnActionPerformed

    private void sil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_btnActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) hastaTablosu.getModel();
        int secili_row = hastaTablosu.getSelectedRow();
        
        if(secili_row == -1){
            if(hastaTablosu.getRowCount() != 0){
                JOptionPane.showMessageDialog(this, "SİLİNECEK HASTAYI SEÇİNİZ");  
            } 
        }
        else{
            model.removeRow(secili_row);
        }
       
        
        
        
    }//GEN-LAST:event_sil_btnActionPerformed

    private void hastaTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaTablosuMouseClicked
         
        DefaultTableModel model = (DefaultTableModel) hastaTablosu.getModel();
        int secili_row = hastaTablosu.getSelectedRow();
        
        tcField.setText(model.getValueAt(secili_row, 0).toString());
        teshisField.setText(model.getValueAt(secili_row, 1).toString());
        ilacField.setText(model.getValueAt(secili_row, 2).toString());
        randevuField.setText(model.getValueAt(secili_row, 3).toString());
    }//GEN-LAST:event_hastaTablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaglikCalisaniGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaglikCalisaniGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaglikCalisaniGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaglikCalisaniGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaglikCalisaniGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geriyeDon;
    private javax.swing.JButton guncelle_btn;
    private javax.swing.JButton hastaEkle_btn;
    private javax.swing.JTable hastaTablosu;
    private javax.swing.JLabel hasta_tc_label;
    private javax.swing.JTextField ilacField;
    private javax.swing.JLabel ilac_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField randevuField;
    private javax.swing.JLabel randevu_label;
    private javax.swing.JButton sil_btn;
    private javax.swing.JTextField tcField;
    private javax.swing.JTextField teshisField;
    private javax.swing.JLabel teshis_label;
    // End of variables declaration//GEN-END:variables
}
